apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-kafka-keda
  namespace: app-ns
spec:
  scaleTargetRef:
    kind: Deployment
    name: nginx-deployment
  minReplicaCount: 3
  maxReplicaCount: 10
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc:9092 
      topic: nginx-events
      consumerGroup: nginx-consumer
      lagThreshold: "5"